
use cdat_qa_queue;


DROP TABLE SMPL_APLCTN_MOD_QUE_WORK_STP_EXCLSN;

CREATE TABLE SMPL_APLCTN_MOD_QUE_WORK_STP_EXCLSN
(
	SMPL_APLCTN_MOD_QUE_WORK_STP_EXCLSN_ID BIGINT NOT NULL AUTO_INCREMENT,
	EXCLDD_AT_SMPL_APLCTN_MOD_QUE_WORK_STP_ID BIGINT NOT NULL,
	PROCD_AT_SMPL_APLCTN_MOD_QUE_WORK_STP_ID BIGINT NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            BIGINT NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             BIGINT NULL,
	PRIMARY KEY (SMPL_APLCTN_MOD_QUE_WORK_STP_EXCLSN_ID),
	FOREIGN KEY SMPL_APLCTN_MOD_QUE_WORK_STP_EXCLSN_FK162 (PROCD_AT_SMPL_APLCTN_MOD_QUE_WORK_STP_ID) REFERENCES SMPL_APLCTN_MOD_QUE_WORK_STP (SMPL_APLCTN_MOD_QUE_WORK_STP_ID),
	FOREIGN KEY SMPL_APLCTN_MOD_QUE_WORK_STP_EXCLSN_FK163 (EXCLDD_AT_SMPL_APLCTN_MOD_QUE_WORK_STP_ID) REFERENCES SMPL_APLCTN_MOD_QUE_WORK_STP (SMPL_APLCTN_MOD_QUE_WORK_STP_ID)
);

CREATE UNIQUE INDEX SMPL_APLCTN_MOD_QUE_WORK_STP_EXCLSN_PK ON SMPL_APLCTN_MOD_QUE_WORK_STP_EXCLSN
(
	SMPL_APLCTN_MOD_QUE_WORK_STP_EXCLSN_ID ASC
);

CREATE INDEX SMPL_APLCTN_MOD_QUE_WORK_STP_EXCLSN_FK1 ON SMPL_APLCTN_MOD_QUE_WORK_STP_EXCLSN
(
	PROCD_AT_SMPL_APLCTN_MOD_QUE_WORK_STP_ID ASC
);

CREATE INDEX SMPL_APLCTN_MOD_QUE_WORK_STP_EXCLSN_FK2 ON SMPL_APLCTN_MOD_QUE_WORK_STP_EXCLSN
(
	EXCLDD_AT_SMPL_APLCTN_MOD_QUE_WORK_STP_ID ASC
);

grant select, update, insert, delete on SMPL_APLCTN_MOD_QUE_WORK_STP_EXCLSN to cdat_app_queue;