use cdat_qa_pp;


DROP TABLE RFRNC_GNDR;

CREATE TABLE RFRNC_GNDR
(
	GNDR_ID              BIGINT NOT NULL AUTO_INCREMENT,
	GNDR_NAME            VARCHAR(300) NOT NULL,
	GNDR_DESC            VARCHAR(500) NOT NULL,
	CREATD_BY            BIGINT NULL,
	MDFYD_BY             BIGINT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MDFYD_DT             DATETIME NULL,
	PRIMARY KEY (GNDR_ID)
);

CREATE UNIQUE INDEX RFRNC_GNDR_PK ON RFRNC_GNDR
(
	GNDR_ID ASC
);

DROP TABLE RFRNC_FIL_FRMT_ISS;

CREATE TABLE RFRNC_FIL_FRMT_ISS
(
	FIL_FRMT_ISS_ID      BIGINT NOT NULL AUTO_INCREMENT,
	FIL_FRMT_ISS_NAME    VARCHAR(300) NOT NULL,
	FIL_FRMT_ISS_DESC    VARCHAR(500) NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            BIGINT NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             BIGINT NULL,
	PRIMARY KEY (FIL_FRMT_ISS_ID)
);

CREATE UNIQUE INDEX RFRNC_FIL_FRMT_ISS_PK ON RFRNC_FIL_FRMT_ISS
(
	FIL_FRMT_ISS_ID ASC
);


grant select, update, insert, delete on RFRNC_FIL_FRMT_ISS to cdat_app_pp;
grant select, update, insert, delete on RFRNC_GNDR to cdat_app_pp;



use cdat_qa_pp;

alter table USER_CNTRCT ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

alter table USER_CNTRCT ADD CREATD_BY BIGINT;

alter table USER_CNTRCT ADD MDFYD_DT DATETIME;

alter table USER_CNTRCT ADD MDFYD_BY BIGINT;

alter table ENRLEE_IDENT ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

alter table ENRLEE_IDENT ADD CREATD_BY BIGINT;

alter table ENRLEE_IDENT ADD MDFYD_DT DATETIME;

alter table ENRLEE_IDENT ADD MDFYD_BY BIGINT;

alter table RFRNC_ENRLEE_IDENT_TYPE ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

alter table RFRNC_ENRLEE_IDENT_TYPE ADD CREATD_BY BIGINT;

alter table RFRNC_ENRLEE_IDENT_TYPE ADD MDFYD_DT DATETIME;

alter table RFRNC_ENRLEE_IDENT_TYPE ADD MDFYD_BY BIGINT;

alter table ENRLEE_HCC_DGNS_CD ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

alter table ENRLEE_HCC_DGNS_CD ADD CREATD_BY BIGINT;

alter table ENRLEE_HCC_DGNS_CD ADD MDFYD_DT DATETIME;

alter table ENRLEE_HCC_DGNS_CD ADD MDFYD_BY BIGINT;

alter table RFRNC_DGNS_CD_TYPE ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

alter table RFRNC_DGNS_CD_TYPE ADD CREATD_BY BIGINT;

alter table RFRNC_DGNS_CD_TYPE ADD MDFYD_DT DATETIME;

alter table RFRNC_DGNS_CD_TYPE ADD MDFYD_BY BIGINT;

#alter table COVERSHEET_VRSN_ENRLEE_HCC ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

#alter table COVERSHEET_VRSN_ENRLEE_HCC ADD CREATD_BY BIGINT;

#alter table COVERSHEET_VRSN_ENRLEE_HCC ADD MDFYD_DT DATETIME;

#alter table COVERSHEET_VRSN_ENRLEE_HCC ADD MDFYD_BY BIGINT;

alter table ENRLEE_HCC ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

alter table ENRLEE_HCC ADD CREATD_BY BIGINT;

alter table ENRLEE_HCC ADD MDFYD_DT DATETIME;

alter table ENRLEE_HCC ADD MDFYD_BY BIGINT;

alter table COVERSHEET_MDCL_REC_VLDTN ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

#alter table COVERSHEET_MDCL_REC_VLDTN ADD CREATD_BY BIGINT;

alter table COVERSHEET_MDCL_REC_VLDTN ADD MDFYD_DT DATETIME;

alter table COVERSHEET_MDCL_REC_VLDTN ADD MDFYD_BY BIGINT;

#alter table COVERSHEET_VRSN ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

#alter table COVERSHEET_VRSN ADD CREATD_BY BIGINT;

#alter table COVERSHEET_VRSN ADD MDFYD_DT DATETIME;

#alter table COVERSHEET_VRSN ADD MDFYD_BY BIGINT;


#alter table RFRNC_PRVDR_TYPE ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

#alter table RFRNC_PRVDR_TYPE ADD CREATD_BY BIGINT;

#alter table RFRNC_PRVDR_TYPE ADD MDFYD_DT DATETIME;

#alter table RFRNC_PRVDR_TYPE ADD MDFYD_BY BIGINT;

#alter table RFRNC_UPLD_TYPE ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

#alter table RFRNC_UPLD_TYPE ADD CREATD_BY BIGINT;

#alter table RFRNC_UPLD_TYPE ADD MDFYD_DT DATETIME;

#alter table RFRNC_UPLD_TYPE ADD MDFYD_BY BIGINT;

#alter table COVERSHEET ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

#alter table COVERSHEET ADD CREATD_BY BIGINT;

#alter table COVERSHEET ADD MDFYD_DT DATETIME;

#alter table COVERSHEET ADD MDFYD_BY BIGINT;

#alter table RFRNC_COVERSHEET_SUBMSN_STUS ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

#alter table RFRNC_COVERSHEET_SUBMSN_STUS ADD CREATD_BY BIGINT;

#alter table RFRNC_COVERSHEET_SUBMSN_STUS ADD MDFYD_DT DATETIME;

#alter table RFRNC_COVERSHEET_SUBMSN_STUS ADD MDFYD_BY BIGINT;

alter table ENRLEE ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

# alter table ENRLEE ADD CREATD_BY BIGINT;

alter table ENRLEE ADD MDFYD_DT DATETIME;

# alter table ENRLEE ADD MDFYD_BY BIGINT;

alter table SMPL_CNTRCT ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

alter table SMPL_CNTRCT ADD CREATD_BY BIGINT;

alter table SMPL_CNTRCT ADD MDFYD_DT DATETIME;

alter table SMPL_CNTRCT ADD MDFYD_BY BIGINT;

alter table CNTRCT ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

alter table CNTRCT ADD CREATD_BY BIGINT;

alter table CNTRCT ADD MDFYD_DT DATETIME;

alter table CNTRCT ADD MDFYD_BY BIGINT;

alter table RFRNC_MDCL_REC_VLDTN_RSN ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

alter table RFRNC_MDCL_REC_VLDTN_RSN ADD CREATD_BY BIGINT;

alter table RFRNC_MDCL_REC_VLDTN_RSN ADD MDFYD_DT DATETIME;

alter table RFRNC_MDCL_REC_VLDTN_RSN ADD MDFYD_BY BIGINT;

#alter table PLAN_PRTL_JOB_STUS ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

#alter table PLAN_PRTL_JOB_STUS ADD CREATD_BY BIGINT;

#alter table PLAN_PRTL_JOB_STUS ADD MDFYD_DT DATETIME;

#alter table PLAN_PRTL_JOB_STUS ADD MDFYD_BY BIGINT;

alter table SHEDLOCK ADD CREATD_DT DATETIME NOT NULL DEFAULT current_timestamp;

alter table SHEDLOCK ADD CREATD_BY BIGINT;

alter table SHEDLOCK ADD MDFYD_DT DATETIME;

alter table SHEDLOCK ADD MDFYD_BY BIGINT;

use cdat_qa_pp;

alter table CNTRCT MODIFY CNTRCT_NAME VARCHAR(100);

alter table CNTRCT MODIFY SMPL_YR_HMO_ID VARCHAR(15);

alter table SMPL_CNTRCT MODIFY CRNT_YR_HMO_ID VARCHAR(15);

alter table rfrnc_dgns_cd_type  CHANGE DGNS_TYPE DGNS_CD_TYPE_NAME varchar(300);

alter table rfrnc_enrlee_ident_type CHANGE IDENT_TYPE ENRLEE_IDENT_TYPE_NAME varchar(300);

alter table rfrnc_mdcl_rec_vldtn_rsn CHANGE CMS_DOC_VLDTN_RSN MDCL_REC_VLDTN_RSN_NAME varchar(300);

alter table rfrnc_dgns_cd_type  ADD DGNS_CD_TYPE_DESC VARCHAR(500) ;

alter table rfrnc_enrlee_ident_type  ADD ENRLEE_IDENT_TYPE_DESC VARCHAR(500);

alter table rfrnc_mdcl_rec_vldtn_rsn Add MDCL_REC_VLDTN_RSN_DESC VARCHAR(500) ;

use cdat_qa_pp;

set foreign_key_checks=0;

alter table CNTRCT MODIFY CNTRCT_NAME VARCHAR(100) Not Null;

alter table CNTRCT MODIFY SMPL_YR_HMO_ID VARCHAR(15) Not Null;

alter table CNTRCT MODIFY ORG_ID BIGINT Not Null;

alter table COVERSHEET MODIFY RANK INTEGER Not Null;

alter table COVERSHEET_MDCL_REC_VLDTN MODIFY ACTV_IND TINYINT Not Null;

alter table COVERSHEET_MDCL_REC_VLDTN MODIFY MDCL_REC_VLDTN_RSN_ID BIGINT Not Null;

alter table COVERSHEET_MDCL_REC_VLDTN MODIFY COVERSHEET_VRSN_ID	BIGINT Not Null;

alter table COVERSHEET_VRSN MODIFY SRVC_STRT_DT DATE Not Null;

alter table COVERSHEET_VRSN MODIFY SRVC_END_DT DATE Not Null;

alter table COVERSHEET_VRSN MODIFY FIL_FRMT_ISS_IND BIGINT Not Null;

alter table COVERSHEET_VRSN MODIFY VLDTN_DT DATETIME Not Null;

alter table COVERSHEET_VRSN MODIFY COVERSHEET_ID BIGINT	Not Null;

alter table COVERSHEET_VRSN MODIFY CRNT_IND TINYINT Not Null;

alter table COVERSHEET_VRSN MODIFY DOC_MDCL_REC_ID BIGINT Not Null;

alter table ENRLEE_HCC MODIFY  HCC VARCHAR(10) Not Null;

alter table ENRLEE_HCC_DGNS_CD MODIFY DGNS_CD VARCHAR(10) Not Null;

alter table ENRLEE_HCC_DGNS_CD MODIFY DSPLY_ORDR INTEGER Not Null;

alter table ENRLEE_HCC_DGNS_CD MODIFY DGNS_TYPE_ID BIGINT Not Null;

alter table ENRLEE_HCC_DGNS_CD MODIFY ENRLEE_HCC_ID BIGINT Not Null;

alter table ENRLEE_HCC_DGNS_CD	 MODIFY HCC_MODEL_YR INTEGER Not Null;

alter table SMPL_CNTRCT	MODIFY CNTRCT_ID BIGINT Not Null;

alter table SMPL_CNTRCT MODIFY 	SMPL_ID	BIGINT Not Null;

alter table SMPL_CNTRCT MODIFY 	CRNT_YR_HMO_ID VARCHAR(15) Not Null;

alter table USER_CNTRCT	MODIFY CNTRCT_ID BIGINT Not Null;

alter table USER_CNTRCT MODIFY 	USER_ID	BIGINT Not Null;

set foreign_key_checks=1;

use cdat_qa_pp;

alter table COVERSHEET_VRSN MODIFY DOC_MDCL_REC_ID BIGINT  Null;

alter table COVERSHEET_VRSN MODIFY FIL_FRMT_ISS_IND BIGINT  Null;

alter table COVERSHEET_VRSN MODIFY SRVC_STRT_DT DATE  Null;

alter table COVERSHEET_VRSN MODIFY SRVC_END_DT DATE  Null;




