use cdat_ivnv_intake;

DROP TABLE WORK_STP_CMT;

DROP TABLE RFRNC_WORK_STP_CMT_TYPE;

DROP TABLE INVLD_MDCL_REC_QSTN_NON_CMPLNC_RSN;

DROP TABLE RFRNC_MDCL_REC_NON_CMPLNC_RSN;

DROP TABLE RFRNC_INVLD_MDCL_REC_QSTN;

DROP TABLE EVALTN_WORK_STP_INVLD_ATSTTN_RSN;

DROP TABLE RFRNC_INVLD_ATSTTN_RSN;

DROP TABLE EVALTN_WORK_STP_INVLD_MDCL_REC_RSN;

DROP TABLE RFRNC_INVLD_MDCL_REC_RSN;

DROP TABLE PAGE_MANIPULATION;

DROP TABLE EVALTN_WORK_STP;

DROP TABLE RFRNC_EVALTN_WORK_STP_STUS;

DROP TABLE RFRNC_ATSTTN_TYPE;

DROP TABLE RFRNC_MDCL_REC_TYPE;

CREATE TABLE RFRNC_MDCL_REC_TYPE
(
	MDCL_REC_TYPE_ID     BIGINT NOT NULL AUTO_INCREMENT,
	MDCL_REC_TYPE_NAME   VARCHAR(300) NOT NULL,
	MDCL_REC_TYPE_DESC   VARCHAR(500) NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            INTEGER NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             INTEGER NULL,
	PRIMARY KEY (MDCL_REC_TYPE_ID)
);

CREATE UNIQUE INDEX RFRNC_MDCL_REC_TYPE_PK ON RFRNC_MDCL_REC_TYPE
(
	MDCL_REC_TYPE_ID ASC
);

CREATE TABLE RFRNC_ATSTTN_TYPE
(
	ATSTTN_TYPE_ID       BIGINT NOT NULL AUTO_INCREMENT,
	ATSTTN_TYPE_NAME     VARCHAR(300) NOT NULL,
	ATSTTN_TYPE_DESC     VARCHAR(500) NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            INTEGER NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             INTEGER NULL,
	PRIMARY KEY (ATSTTN_TYPE_ID)
);

CREATE UNIQUE INDEX RFRNC_ATSTTN_TYPE_PK ON RFRNC_ATSTTN_TYPE
(
	ATSTTN_TYPE_ID ASC
);

CREATE TABLE RFRNC_EVALTN_WORK_STP_STUS
(
	EVALTN_WORK_STP_STUS_ID BIGINT NOT NULL,
	EVALTN_WORK_STP_STUS_NAME VARCHAR(300) NOT NULL,
	EVALTN_WORK_STP_STUS_DESC VARCHAR(500) NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            INTEGER NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             INTEGER NULL,
	PRIMARY KEY (EVALTN_WORK_STP_STUS_ID)
);

CREATE UNIQUE INDEX RFRNC_EVALTN_WORK_STP_STUS_PK ON RFRNC_EVALTN_WORK_STP_STUS
(
	EVALTN_WORK_STP_STUS_ID ASC
);

CREATE TABLE EVALTN_WORK_STP
(
	EVALTN_WORK_STP_ID   BIGINT NOT NULL AUTO_INCREMENT,
	EVALTN_WORK_STP_STUS_ID BIGINT NOT NULL,
	SMPL_APLCTN_MOD_QUE_WORK_STP_ID BIGINT NOT NULL,
	ATSTTN_DOS           DATE NULL,
	ATSTTN_TYPE_ID       BIGINT NULL,
	MDCL_REC_TYPE_ID     BIGINT NULL,
	MDCL_REC_ADMSN_DT    DATE NULL,
	MDCL_REC_DSCHRG_DT   DATE NULL,
	COVERSHEET_ID        BIGINT NULL,
	USER_ID              BIGINT NULL,
	ACTV_IND             TINYINT NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            INTEGER NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             INTEGER NULL,
	PRIMARY KEY (EVALTN_WORK_STP_ID),
	FOREIGN KEY EVALTN_WORK_STP_FK151 (ATSTTN_TYPE_ID) REFERENCES RFRNC_ATSTTN_TYPE (ATSTTN_TYPE_ID),
	FOREIGN KEY EVALTN_WORK_STP_FK150 (MDCL_REC_TYPE_ID) REFERENCES RFRNC_MDCL_REC_TYPE (MDCL_REC_TYPE_ID),
	FOREIGN KEY EVALTN_WORK_STP_FK159 (EVALTN_WORK_STP_STUS_ID) REFERENCES RFRNC_EVALTN_WORK_STP_STUS (EVALTN_WORK_STP_STUS_ID)
);

CREATE UNIQUE INDEX EVALTN_WORK_STP_PK ON EVALTN_WORK_STP
(
	EVALTN_WORK_STP_ID ASC
);

CREATE INDEX EVALTN_WORK_STP_FK7 ON EVALTN_WORK_STP
(
	ATSTTN_TYPE_ID ASC
);

CREATE INDEX EVALTN_WORK_STP_FK8 ON EVALTN_WORK_STP
(
	MDCL_REC_TYPE_ID ASC
);

CREATE INDEX EVALTN_WORK_STP_FK9 ON EVALTN_WORK_STP
(
	COVERSHEET_ID ASC
);

CREATE INDEX EVALTN_WORK_STP_FK10 ON EVALTN_WORK_STP
(
	USER_ID ASC
);

CREATE INDEX EVALTN_WORK_STP_FK11 ON EVALTN_WORK_STP
(
	SMPL_APLCTN_MOD_QUE_WORK_STP_ID ASC
);

CREATE INDEX EVALTN_WORK_STP_FK12 ON EVALTN_WORK_STP
(
	EVALTN_WORK_STP_STUS_ID ASC
);

CREATE TABLE PAGE_MANIPULATION
(
	PAGE_MANIPULATION_ID BIGINT NOT NULL AUTO_INCREMENT,
	EVALTN_WORK_STP_ID   BIGINT NOT NULL,
	PAGE_ID              BIGINT NULL,
	PAGE_NUM             BIGINT NULL,
	ROT                  BIGINT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            INTEGER NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             INTEGER NULL,
	PRIMARY KEY (PAGE_MANIPULATION_ID),
	FOREIGN KEY PAGE_MANIPULATION_FK161 (EVALTN_WORK_STP_ID) REFERENCES EVALTN_WORK_STP (EVALTN_WORK_STP_ID)
);

CREATE UNIQUE INDEX PAGE_MANIPULATION_PK ON PAGE_MANIPULATION
(
	PAGE_MANIPULATION_ID ASC
);

CREATE INDEX PAGE_MANIPULATION_FK1 ON PAGE_MANIPULATION
(
	EVALTN_WORK_STP_ID ASC
);

CREATE TABLE RFRNC_INVLD_MDCL_REC_RSN
(
	INVLD_MDCL_REC_RSN_ID BIGINT NOT NULL AUTO_INCREMENT,
	INVLD_MDCL_REC_RSN_NAME VARCHAR(300) NOT NULL,
	INVLD_MDCL_REC_RSN_DESC VARCHAR(500) NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            INTEGER NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             INTEGER NULL,
	PRIMARY KEY (INVLD_MDCL_REC_RSN_ID)
);

CREATE UNIQUE INDEX RFRNC_INVLD_MDCL_REC_RSN_PK ON RFRNC_INVLD_MDCL_REC_RSN
(
	INVLD_MDCL_REC_RSN_ID ASC
);

CREATE TABLE EVALTN_WORK_STP_INVLD_MDCL_REC_RSN
(
	EVALTN_WORK_STP_INVLD_MDCL_REC_RSN_ID BIGINT NOT NULL AUTO_INCREMENT,
	INVLD_MDCL_REC_RSN_ID BIGINT NULL,
	EVALTN_WORK_STP_ID   BIGINT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            INTEGER NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             INTEGER NULL,
	PRIMARY KEY (EVALTN_WORK_STP_INVLD_MDCL_REC_RSN_ID),
	FOREIGN KEY EVALTN_WORK_STP_INVLD_MDCL_REC_RSN_FK152 (INVLD_MDCL_REC_RSN_ID) REFERENCES RFRNC_INVLD_MDCL_REC_RSN (INVLD_MDCL_REC_RSN_ID),
	FOREIGN KEY EVALTN_WORK_STP_INVLD_MDCL_REC_RSN_FK153 (EVALTN_WORK_STP_ID) REFERENCES EVALTN_WORK_STP (EVALTN_WORK_STP_ID)
);

CREATE UNIQUE INDEX EVALTN_WORK_STP_INVLD_MDCL_REC_RSN_PK ON EVALTN_WORK_STP_INVLD_MDCL_REC_RSN
(
	EVALTN_WORK_STP_INVLD_MDCL_REC_RSN_ID ASC
);

CREATE INDEX EVALTN_WORK_STP_INVLD_MDCL_REC_RSN_FK1 ON EVALTN_WORK_STP_INVLD_MDCL_REC_RSN
(
	INVLD_MDCL_REC_RSN_ID ASC
);

CREATE INDEX EVALTN_WORK_STP_INVLD_MDCL_REC_RSN_FK2 ON EVALTN_WORK_STP_INVLD_MDCL_REC_RSN
(
	EVALTN_WORK_STP_ID ASC
);

CREATE TABLE RFRNC_INVLD_ATSTTN_RSN
(
	INVLD_ATSTTN_RSN_ID  BIGINT NOT NULL AUTO_INCREMENT,
	INVLD_ATSTTN_RSN_NAME VARCHAR(300) NOT NULL,
	INVLD_ATTESATTION_RSN_DESC VARCHAR(500) NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            INTEGER NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             INTEGER NULL,
	PRIMARY KEY (INVLD_ATSTTN_RSN_ID)
);

CREATE UNIQUE INDEX RFRNC_INVLD_ATSTTN_RSN_PK ON RFRNC_INVLD_ATSTTN_RSN
(
	INVLD_ATSTTN_RSN_ID ASC
);

CREATE TABLE EVALTN_WORK_STP_INVLD_ATSTTN_RSN
(
	EVALTN_WORK_STP_INVLD_ATSTTN_RSN_ID BIGINT NOT NULL AUTO_INCREMENT,
	EVALTN_WORK_STP_ID   BIGINT NULL,
	INVLD_ATSTTN_RSN_ID  BIGINT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            INTEGER NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             INTEGER NULL,
	PRIMARY KEY (EVALTN_WORK_STP_INVLD_ATSTTN_RSN_ID),
	FOREIGN KEY EVALTN_WORK_STP_INVLD_ATSTTN_RSN_FK145 (EVALTN_WORK_STP_ID) REFERENCES EVALTN_WORK_STP (EVALTN_WORK_STP_ID),
	FOREIGN KEY EVALTN_WORK_STP_INVLD_ATSTTN_RSN_FK146 (INVLD_ATSTTN_RSN_ID) REFERENCES RFRNC_INVLD_ATSTTN_RSN (INVLD_ATSTTN_RSN_ID)
);

CREATE UNIQUE INDEX EVALTN_WORK_STP_INVLD_ATSTTN_RSN_PK ON EVALTN_WORK_STP_INVLD_ATSTTN_RSN
(
	EVALTN_WORK_STP_INVLD_ATSTTN_RSN_ID ASC
);

CREATE INDEX EVALTN_WORK_STP_INVLD_ATSTTN_RSN_FK1 ON EVALTN_WORK_STP_INVLD_ATSTTN_RSN
(
	EVALTN_WORK_STP_ID ASC
);

CREATE INDEX EVALTN_WORK_STP_INVLD_ATSTTN_RSN_FK2 ON EVALTN_WORK_STP_INVLD_ATSTTN_RSN
(
	INVLD_ATSTTN_RSN_ID ASC
);

CREATE TABLE RFRNC_INVLD_MDCL_REC_QSTN
(
	INVLD_MDCL_REC_QSTN_ID BIGINT NOT NULL AUTO_INCREMENT,
	INVLD_MDCL_REC_QSTN_NAME VARCHAR(300) NOT NULL,
	INVLD_MDCL_REC_QSTN_DESC VARCHAR(500) NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            INTEGER NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             INTEGER NULL,
	PRIMARY KEY (INVLD_MDCL_REC_QSTN_ID)
);

CREATE UNIQUE INDEX RFRNC_INVLD_MDCL_REC_QSTN_PK ON RFRNC_INVLD_MDCL_REC_QSTN
(
	INVLD_MDCL_REC_QSTN_ID ASC
);

CREATE TABLE RFRNC_MDCL_REC_NON_CMPLNC_RSN
(
	MDCL_REC_NON_CMPLNC_RSN_ID BIGINT NOT NULL AUTO_INCREMENT,
	MDCL_REC_NON_CMPLNC_RSN_NAME VARCHAR(300) NOT NULL,
	MDCL_REC_NON_CMPLNC_RSN_DESC VARCHAR(500) NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            INTEGER NULL,
	MDFYD_BY             INTEGER NULL,
	MDFYD_DT             DATETIME NULL,
	PRIMARY KEY (MDCL_REC_NON_CMPLNC_RSN_ID)
);

CREATE UNIQUE INDEX RFRNC_MDCL_REC_NON_CMPLNC_RSN_PK ON RFRNC_MDCL_REC_NON_CMPLNC_RSN
(
	MDCL_REC_NON_CMPLNC_RSN_ID ASC
);

CREATE TABLE INVLD_MDCL_REC_QSTN_NON_CMPLNC_RSN
(
	INVLD_MDCL_REC_QSTN_NON_CMPLNC_RSN_ID BIGINT NOT NULL AUTO_INCREMENT,
	INVLD_MDCL_REC_QSTN_ID BIGINT NULL,
	RSPNS                CHAR(18) NULL,
	EVALTN_WORK_STP_ID   BIGINT NULL,
	MDCL_REC_NON_CMPLNC_RSN_ID BIGINT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            INTEGER NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             INTEGER NULL,
	PRIMARY KEY (INVLD_MDCL_REC_QSTN_NON_CMPLNC_RSN_ID),
	FOREIGN KEY INVLD_MDCL_REC_QSTN_NON_CMPLNC_RSN_FK140 (INVLD_MDCL_REC_QSTN_ID) REFERENCES RFRNC_INVLD_MDCL_REC_QSTN (INVLD_MDCL_REC_QSTN_ID),
	FOREIGN KEY INVLD_MDCL_REC_QSTN_NON_CMPLNC_RSN_FK143 (EVALTN_WORK_STP_ID) REFERENCES EVALTN_WORK_STP (EVALTN_WORK_STP_ID),
	FOREIGN KEY INVLD_MDCL_REC_QSTN_NON_CMPLNC_RSN_FK147 (MDCL_REC_NON_CMPLNC_RSN_ID) REFERENCES RFRNC_MDCL_REC_NON_CMPLNC_RSN (MDCL_REC_NON_CMPLNC_RSN_ID)
);

CREATE UNIQUE INDEX INVLD_MDCL_REC_QSTN_NON_CMPLNC_RSN_PK ON INVLD_MDCL_REC_QSTN_NON_CMPLNC_RSN
(
	INVLD_MDCL_REC_QSTN_NON_CMPLNC_RSN_ID ASC
);

CREATE INDEX INVLD_MDCL_REC_QSTN_NON_CMPLNC_RSN_FK2 ON INVLD_MDCL_REC_QSTN_NON_CMPLNC_RSN
(
	INVLD_MDCL_REC_QSTN_ID ASC
);

CREATE INDEX INVLD_MDCL_REC_QSTN_NON_CMPLNC_RSN_FK3 ON INVLD_MDCL_REC_QSTN_NON_CMPLNC_RSN
(
	EVALTN_WORK_STP_ID ASC
);

CREATE INDEX INVLD_MDCL_REC_QSTN_NON_CMPLNC_RSN_FK4 ON INVLD_MDCL_REC_QSTN_NON_CMPLNC_RSN
(
	MDCL_REC_NON_CMPLNC_RSN_ID ASC
);

CREATE TABLE RFRNC_WORK_STP_CMT_TYPE
(
	WORK_STP_CMT_TYPE_ID BIGINT NOT NULL,
	WORK_STP_CMT_TYPE_NAME VARCHAR(300) NOT NULL,
	WORK_STP_CMT_TYPE_DESC VARCHAR(500) NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            INTEGER NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             CHAR(18) NULL,
	PRIMARY KEY (WORK_STP_CMT_TYPE_ID)
);

CREATE UNIQUE INDEX RFRNC_WORK_STP_CMT_TYPE_PK ON RFRNC_WORK_STP_CMT_TYPE
(
	WORK_STP_CMT_TYPE_ID ASC
);

CREATE TABLE WORK_STP_CMT
(
	WORK_STP_CMT_ID      BIGINT NOT NULL AUTO_INCREMENT,
	WORK_STP_CMT_TYPE_ID BIGINT NOT NULL,
	EVALTN_WORK_STP_ID   BIGINT NULL,
	CMT                  VARCHAR(3500) NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            INTEGER NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             INTEGER NULL,
	PRIMARY KEY (WORK_STP_CMT_ID),
	FOREIGN KEY WORK_STP_CMT_FK144 (EVALTN_WORK_STP_ID) REFERENCES EVALTN_WORK_STP (EVALTN_WORK_STP_ID),
	FOREIGN KEY WORK_STP_CMT_FK160 (WORK_STP_CMT_TYPE_ID) REFERENCES RFRNC_WORK_STP_CMT_TYPE (WORK_STP_CMT_TYPE_ID)
);

CREATE UNIQUE INDEX WORK_STP_CMT_PK ON WORK_STP_CMT
(
	WORK_STP_CMT_ID ASC
);

CREATE INDEX WORK_STP_CMT_FK1 ON WORK_STP_CMT
(
	EVALTN_WORK_STP_ID ASC
);

CREATE INDEX WORK_STP_CMT_FK2 ON WORK_STP_CMT
(
	WORK_STP_CMT_TYPE_ID ASC
);
