
use cdat_ivnv_queue;


DROP TABLE QUE_TRANS_LOG;

DROP TABLE SMPL_APLCTN_MOD_QUE_WORK_STP;

DROP TABLE RFRNC_APLCTN_MOD;

DROP TABLE RFRNC_QUE_WORK_PHASE;

DROP TABLE ORG_QUE_WORK_STP;

DROP TABLE RFRNC_QUE_WORK_STP;

CREATE TABLE RFRNC_QUE_WORK_STP
(
	QUE_WORK_STP_ID      BIGINT NOT NULL AUTO_INCREMENT,
	QUE_WORK_STP_NAME    VARCHAR(300) NOT NULL,
	QUE_WORK_STP_DESC    VARCHAR(500) NOT NULL,
	QUE_DSPLY_NAME       VARCHAR(50) NULL,
	SCRTY_ID             BIGINT NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            BIGINT NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             BIGINT NULL,
	PRIMARY KEY (QUE_WORK_STP_ID)
);

CREATE UNIQUE INDEX RFRNC_QUE_WORK_STP_PK ON RFRNC_QUE_WORK_STP
(
	QUE_WORK_STP_ID ASC
);

CREATE INDEX RFRNC_QUE_WORK_STP_FK1 ON RFRNC_QUE_WORK_STP
(
	SCRTY_ID ASC
);

CREATE TABLE ORG_QUE_WORK_STP
(
	ORG_QUE_WORK_STP_ID  BIGINT NOT NULL AUTO_INCREMENT,
	ORG_ID               BIGINT NOT NULL,
	QUE_WORK_STP_ID      BIGINT NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            BIGINT NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             BIGINT NULL,
	PRIMARY KEY (ORG_QUE_WORK_STP_ID),
	FOREIGN KEY ORG_QUE_WORK_STP_FK122 (QUE_WORK_STP_ID) REFERENCES RFRNC_QUE_WORK_STP (QUE_WORK_STP_ID)
);

CREATE UNIQUE INDEX ORG_QUE_WORK_STP_PK ON ORG_QUE_WORK_STP
(
	ORG_QUE_WORK_STP_ID ASC
);

CREATE INDEX ORG_QUE_WORK_STP_FK1 ON ORG_QUE_WORK_STP
(
	ORG_ID ASC
);

CREATE INDEX ORG_QUE_WORK_STP_FK2 ON ORG_QUE_WORK_STP
(
	QUE_WORK_STP_ID ASC
);

CREATE TABLE RFRNC_QUE_WORK_PHASE
(
	QUE_WORK_PHASE_ID    BIGINT NOT NULL AUTO_INCREMENT,
	QUE_WORK_PHASE_NAME  VARCHAR(300) NOT NULL,
	QUE_WORK_PHASE_DESC  VARCHAR(500) NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            BIGINT NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             BIGINT NULL,
	PRIMARY KEY (QUE_WORK_PHASE_ID)
);

CREATE UNIQUE INDEX RFRNC_QUE_WORK_PHASE_PK ON RFRNC_QUE_WORK_PHASE
(
	QUE_WORK_PHASE_ID ASC
);

CREATE TABLE RFRNC_APLCTN_MOD
(
	APLCTN_MOD_ID        BIGINT NOT NULL AUTO_INCREMENT,
	APLCTN_MOD_NAME      VARCHAR(300) NOT NULL,
	APLCTN_MOD_DESC      VARCHAR(500) NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            BIGINT NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             BIGINT NULL,
	PRIMARY KEY (APLCTN_MOD_ID)
);

CREATE UNIQUE INDEX RFRNC_APLCTN_MOD_PK ON RFRNC_APLCTN_MOD
(
	APLCTN_MOD_ID ASC
);

CREATE TABLE SMPL_APLCTN_MOD_QUE_WORK_STP
(
	SMPL_APLCTN_MOD_QUE_WORK_STP_ID BIGINT NOT NULL AUTO_INCREMENT,
	APLCTN_MOD_ID        BIGINT NOT NULL,
	QUE_WORK_STP_ID      BIGINT NOT NULL,
	SMPL_ID              BIGINT NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            BIGINT NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             BIGINT NULL,
	PRIMARY KEY (SMPL_APLCTN_MOD_QUE_WORK_STP_ID),
	FOREIGN KEY SMPL_APLCTN_MOD_QUE_WORK_STP_FK115 (APLCTN_MOD_ID) REFERENCES RFRNC_APLCTN_MOD (APLCTN_MOD_ID),
	FOREIGN KEY SMPL_APLCTN_MOD_QUE_WORK_STP_FK116 (QUE_WORK_STP_ID) REFERENCES RFRNC_QUE_WORK_STP (QUE_WORK_STP_ID)
);

CREATE UNIQUE INDEX SMPL_APLCTN_MOD_QUE_WORK_STP_PK ON SMPL_APLCTN_MOD_QUE_WORK_STP
(
	SMPL_APLCTN_MOD_QUE_WORK_STP_ID ASC
);

CREATE INDEX SMPL_APLCTN_MOD_QUE_WORK_STP_FK1 ON SMPL_APLCTN_MOD_QUE_WORK_STP
(
	APLCTN_MOD_ID ASC
);

CREATE INDEX SMPL_APLCTN_MOD_QUE_WORK_STP_FK2 ON SMPL_APLCTN_MOD_QUE_WORK_STP
(
	QUE_WORK_STP_ID ASC
);

CREATE INDEX SMPL_APLCTN_MOD_QUE_WORK_STP_FK3 ON SMPL_APLCTN_MOD_QUE_WORK_STP
(
	SMPL_ID ASC
);

CREATE TABLE QUE_TRANS_LOG
(
	QUE_TRANS_LOG_ID     BIGINT NOT NULL AUTO_INCREMENT,
	ACTV_STP_IND         TINYINT NOT NULL,
	QUE_WORK_PHASE_ID    BIGINT NOT NULL,
	COVERSHEET_ID        BIGINT NOT NULL,
	USER_ID              BIGINT NOT NULL,
	NOTES                VARCHAR(400) NULL,
	EVNT_DT              DATETIME NULL,
	ESCAL_PRNT           BIGINT NOT NULL,
	ESCAL_CMPLT_IND      TINYINT NOT NULL,
	RSET_IND             TINYINT NOT NULL,
	ORG_ID               BIGINT NOT NULL,
	SMPL_APLCTN_MOD_QUE_WORK_STP_ID BIGINT NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            BIGINT NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             BIGINT NULL,
	PRIMARY KEY (QUE_TRANS_LOG_ID),
	FOREIGN KEY QUE_TRANS_LOG_FK119 (QUE_WORK_PHASE_ID) REFERENCES RFRNC_QUE_WORK_PHASE (QUE_WORK_PHASE_ID),
	FOREIGN KEY QUE_TRANS_LOG_FK134 (SMPL_APLCTN_MOD_QUE_WORK_STP_ID) REFERENCES SMPL_APLCTN_MOD_QUE_WORK_STP (SMPL_APLCTN_MOD_QUE_WORK_STP_ID)
);

CREATE UNIQUE INDEX QUE_TRANS_LOG_PK ON QUE_TRANS_LOG
(
	QUE_TRANS_LOG_ID ASC
);

CREATE INDEX QUE_TRANS_LOG_FK3 ON QUE_TRANS_LOG
(
	QUE_WORK_PHASE_ID ASC
);

CREATE INDEX QUE_TRANS_LOG_FK4 ON QUE_TRANS_LOG
(
	COVERSHEET_ID ASC
);

CREATE INDEX QUE_TRANS_LOG_FK5 ON QUE_TRANS_LOG
(
	ORG_ID ASC
);

CREATE INDEX QUE_TRANS_LOG_FK6 ON QUE_TRANS_LOG
(
	SMPL_APLCTN_MOD_QUE_WORK_STP_ID ASC
);
